update tf workflow (#74)
* update tf workflow

* update pre-commit

* Add a final newline

* Add a final newline

---------

Co-authored-by: Sean Kelly <kelly@seankelly.biz>

diff --git a/.github/workflows/terraform_cicd.yaml b/.github/workflows/terraform_cicd.yaml
--- a/.github/workflows/terraform_cicd.yaml
+++ b/.github/workflows/terraform_cicd.yaml
@@ -1,12 +1,6 @@
 name: 'Terraform-Workflow'
 
-on:
-  push:
-    branches:
-      - '**'
-  pull_request:
-    types: [opened, edited, reopened, ready_for_review, review_requested]
-  workflow_dispatch:
+on: [push, workflow_dispatch]
 
 permissions:
   id-token: write  # required to use OIDC authentication
@@ -28,37 +22,43 @@ jobs:
     - name: Checkout
       uses: actions/checkout@v3
 
-    - name: Configure AWS Credentials
-      uses: aws-actions/configure-aws-credentials@v2
-      with:
-        aws-region: "${{ secrets.AWS_REGION }}"
-        role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
-        role-session-name: PDS_GitHub_OIDC_TERRAFORM
+    # AWS Authentication. Please uncomment this step in your repo to authenticate to AWS.
+
+    # - name: Configure AWS Credentials
+    #   uses: aws-actions/configure-aws-credentials@v2
+    #   with:
+    #     aws-region: "${{ secrets.AWS_REGION }}"
+    #     role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
+    #     role-session-name: PDS_GitHub_OIDC_TERRAFORM
 
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v2
 
-    - name: Terraform Fmt, Init & Validate
-      id: fmt_init_validate
+    - name: Terraform Init
+      id: init
       env:
         AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME}}
         AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME}}
+      run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}"
+
+    - name: Terraform Format & Validate
+      id: fmt_validate
       run: |
         terraform fmt
-        terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}"
         terraform validate -no-color
 
-    - name: Terraform Plan
-      id: plan
-      run: terraform plan -no-color
-      if: github.event_name == 'push' || github.event_name == 'pull_request' # either conditions will trigger a plan
-      continue-on-error:  true
+    # Please uncomment the plan and apply steps below in your terraform worfklow to deploy your infrastructure to AWS.
 
-    - name: Terraform Plan Status
-      id : plan_status
-      if: steps.plan.outcome == 'failure'
-      run: exit 1
+    # - name: Terraform Plan
+    #   id: plan
+    #   run: terraform plan -no-color
+    #   continue-on-error:  true
 
-    - name: Terraform Apply
-      if: github.ref == 'refs/heads/main' && github.event_name == 'push' # both conditions have to be met
-      run: terraform apply -auto-approve
+    # - name: Terraform Plan Status
+    #   id : plan_status
+    #   if: steps.plan.outcome == 'failure'
+    #   run: exit 1
+
+    # - name: Terraform Apply
+    #   if: github.ref == 'refs/heads/main' && github.event_name == 'push' # both conditions have to be met
+    #   run: terraform apply -auto-approve
