Add some checks before the SonarQube step

diff --git a/.github/workflows/unstable-cicd.yaml b/.github/workflows/unstable-cicd.yaml
--- a/.github/workflows/unstable-cicd.yaml
+++ b/.github/workflows/unstable-cicd.yaml
@@ -32,6 +32,7 @@ on:
     push:
         branches:
              - main
+             - issue/118
         paths-ignore:
             - 'CHANGELOG.md'
             - 'docs/requirements/**'
@@ -78,6 +79,17 @@ jobs:
                     pypi_username: ${{secrets.TEST_PYPI_USERNAME}}
                     pypi_password: ${{secrets.TEST_PYPI_PASSWORD}}
                     ADMIN_GITHUB_TOKEN: ${{secrets.ADMIN_GITHUB_TOKEN}}
+            -
+                name: 🔎 Check if coverage.xml got generated
+                run: |
+                    if [ ! -f coverage.xml ]; then
+                        echo "‼️ coverage.xml not found" 1>&2
+                        exit 1
+                    else
+                        echo "🎉 coverage.xml found" 1>&2
+                        ls -l coverage.xml 1>&2
+                    fi
+
             -
                 name: 🛏️ Upload Coverage
                 uses: SonarSource/sonarqube-scan-action@v6
